// Generated by CoffeeScript 1.6.3
(function() {
  var GeopositionSimulator,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GeopositionSimulator = (function() {
    function GeopositionSimulator(options) {
      this.options = options != null ? options : {};
      this.getCurrentPosition = __bind(this.getCurrentPosition, this);
      this.bounds = this.options.bounds != null ? this.options.bounds : {
        start: {
          lat: 33.3,
          lng: 70.5
        },
        radius: 70000
      };
      this.step = this.options.step != null ? this.options.step : 5;
      this.lastPosition = this.bounds.start;
      console.log(this.lastPosition);
    }

    GeopositionSimulator.prototype.generateNewPosition = function() {
      var coords, position;
      coords = {
        latitude: 33.3,
        longitude: 70.5,
        altitude: 0,
        accuracy: 0,
        altitudeAccuracy: 0,
        heading: 0,
        speed: 0
      };
      return position = {
        coords: coords,
        timestamp: new Date().getTime()
      };
    };

    GeopositionSimulator.prototype.getCurrentPosition = function(success, error, options) {
      var newPosition;
      newPosition = this.generateNewPosition();
      return success(newPosition);
    };

    return GeopositionSimulator;

  })();

  window.GeopositionSimulator = GeopositionSimulator;

}).call(this);
