// Generated by CoffeeScript 1.6.3
(function() {
  var geolocation;

  window.simulated_geoposition || (window.simulated_geoposition = {});

  window.simulated_geoposition.geolocation = geolocation = (function() {
    function geolocation() {}

    geolocation.currentSimulator = null;

    geolocation.watchIds = [];

    geolocation.getSimulator = function() {
      if (this.currentSimulator == null) {
        this.currentSimulator = new GeopositionSimulator();
      }
      return this.currentSimulator;
    };

    geolocation.configure = function(options) {
      this.options = options;
    };

    geolocation.getCurrentPosition = function(success, error, options) {
      return this.currentSimulator.getCurrentPosition(success, error, options);
    };

    geolocation.watchPosition = function(success, error, options) {
      var id,
        _this = this;
      id = setInterval((function() {
        return _this.getCurrentPosition(success, error, options);
      }), options.interval);
      this.watchIds.append(id);
      return id;
    };

    geolocation.clearWatch = function(watchId) {
      return clearInterval(watchId);
    };

    return geolocation;

  })();

}).call(this);
